
    create table account (
        attivo boolean not null,
        id integer generated by default as identity,
        ruolo_id integer not null,
        cap varchar(5) not null,
        aggiornato_il timestamp(6),
        creato_il timestamp(6) not null,
        citta varchar(50) not null,
        paese varchar(50) not null,
        cognome varchar(100) not null,
        nome varchar(100) not null,
        via varchar(100) not null,
        primary key (id)
    );

    create table carrello (
        account_id integer not null unique,
        id integer generated by default as identity,
        aggiornato_il timestamp(6),
        creato_il timestamp(6) not null,
        primary key (id)
    );

    create table carrello_riga (
        carrello_id integer not null,
        id integer generated by default as identity,
        prodotto_id integer not null,
        quantita integer not null check (quantita > 0),
        aggiornato_il timestamp(6),
        creato_il timestamp(6) not null,
        primary key (id),
        unique (carrello_id, prodotto_id),
        check (quantita > 0)
    );

    create table categoria (
        attivo boolean not null,
        id integer generated by default as identity,
        aggiornato_il timestamp(6),
        creato_il timestamp(6) not null,
        nome varchar(100) not null unique,
        primary key (id)
    );

    create table credenziale (
        account_id integer unique,
        attivo boolean not null,
        id integer generated by default as identity,
        aggiornato_il timestamp(6),
        creato_il timestamp(6) not null,
        ultimo_login timestamp(6),
        email varchar(255) not null unique,
        password varchar(255) not null,
        primary key (id)
    );

    create table messaggi_sistema (
        code varchar(255) not null,
        lang varchar(255) not null,
        messaggio varchar(255),
        primary key (code, lang)
    );

    create table metodo_pagamento (
        account_id integer not null,
        attivo boolean not null,
        id integer generated by default as identity,
        metodo_default boolean not null,
        tipo_metodo_pagamento_id integer not null,
        aggiornato_il timestamp(6),
        creato_il timestamp(6) not null,
        token varchar(255) not null,
        primary key (id)
    );

    create table ordine (
        account_id integer not null,
        id integer generated by default as identity,
        totale numeric(10,2) not null,
        cap varchar(5) not null,
        aggiornato_il timestamp(6),
        creato_il timestamp(6) not null,
        citta varchar(50) not null,
        paese varchar(50) not null,
        via varchar(100) not null,
        stato_ordine varchar(255) check (stato_ordine in ('IN_ATTESA','PAGATO','SPEDITO','CONSEGNATO','ANNULLATO')),
        primary key (id)
    );

    create table ordine_riga (
        id integer generated by default as identity,
        ordine_id integer not null,
        prezzo_unitario numeric(10,2) not null,
        prodotto_id integer not null,
        quantita integer not null check (quantita > 0),
        aggiornato_il timestamp(6),
        creato_il timestamp(6) not null,
        primary key (id),
        check (quantita > 0)
    );

    create table pagamento (
        id integer generated by default as identity,
        metodo_pagamento_id integer not null,
        ordine_id integer not null unique,
        totale numeric(10,2) not null check (totale > 0),
        aggiornato_il timestamp(6),
        creato_il timestamp(6) not null,
        stato_pagamento varchar(255) not null check (stato_pagamento in ('IN_ATTESA','SUCCESSO','FALLITO')),
        primary key (id)
    );

    create table piattaforma (
        anno_uscita_piattaforma integer not null check (anno_uscita_piattaforma >= 1970 AND anno_uscita_piattaforma <= 2006),
        attivo boolean not null,
        id integer generated by default as identity,
        aggiornato_il timestamp(6),
        creato_il timestamp(6) not null,
        codice varchar(20) not null unique,
        nome varchar(200) not null unique,
        primary key (id)
    );

    create table prodotto (
        anno_uscita integer check (anno_uscita >= 1970 AND anno_uscita <= 2006),
        attivo boolean not null,
        categoria_id integer not null,
        id integer generated by default as identity,
        prezzo numeric(10,2) not null check (prezzo > 0),
        aggiornato_il timestamp(6),
        creato_il timestamp(6) not null,
        sku varchar(50) not null unique,
        nome varchar(200) not null,
        descrizione TEXT not null,
        img_url varchar(255),
        primary key (id)
    );

    create table prodotto_piattaforma (
        piattaforma_id integer not null,
        prodotto_id integer not null,
        primary key (prodotto_id, piattaforma_id)
    );

    create table ruolo (
        attivo boolean not null,
        id integer generated by default as identity,
        aggiornato_il timestamp(6),
        creato_il timestamp(6) not null,
        nome varchar(50) not null unique,
        primary key (id)
    );

    create table tipo_metodo_pagamento (
        attivo boolean not null,
        id integer generated by default as identity,
        aggiornato_il timestamp(6),
        creato_il timestamp(6) not null,
        nome varchar(50) not null unique,
        primary key (id)
    );

    alter table if exists account 
       add constraint FKthdrqbmhk5dp00po3yey8uikk 
       foreign key (ruolo_id) 
       references ruolo;

    alter table if exists carrello 
       add constraint FKqe4cig9fabcp7d4sq1th1opq8 
       foreign key (account_id) 
       references account;

    alter table if exists carrello_riga 
       add constraint FK1kdw3wtgsdr5o2x1xbg7puej0 
       foreign key (carrello_id) 
       references carrello;

    alter table if exists carrello_riga 
       add constraint FK9l12co6tdh4f86puoe17spyky 
       foreign key (prodotto_id) 
       references prodotto;

    alter table if exists credenziale 
       add constraint FKsd0fonwnaypsmwkqag7m1dhvr 
       foreign key (account_id) 
       references account;

    alter table if exists metodo_pagamento 
       add constraint FKyvwfci8m8kma8wxt9hmqyf85 
       foreign key (account_id) 
       references account;

    alter table if exists metodo_pagamento 
       add constraint FKg7p8w0dvjjgrbe9m0xs0ghdgk 
       foreign key (tipo_metodo_pagamento_id) 
       references tipo_metodo_pagamento;

    alter table if exists ordine 
       add constraint FKpy50oev35mxm2shcvuye9likx 
       foreign key (account_id) 
       references account;

    alter table if exists ordine_riga 
       add constraint FKpplo0tcsgv8ypjgblpakdw7ej 
       foreign key (ordine_id) 
       references ordine;

    alter table if exists ordine_riga 
       add constraint FKoqpbw7rwrnsgxrqeu90oo08ue 
       foreign key (prodotto_id) 
       references prodotto;

    alter table if exists pagamento 
       add constraint FKj33asgypvarkf02119piw9o9b 
       foreign key (metodo_pagamento_id) 
       references metodo_pagamento;

    alter table if exists pagamento 
       add constraint FK7vk3ivb6us3276tk9exydpq31 
       foreign key (ordine_id) 
       references ordine;

    alter table if exists prodotto 
       add constraint FKp54y50a2i7pdiipduc60tttrw 
       foreign key (categoria_id) 
       references categoria;

    alter table if exists prodotto_piattaforma 
       add constraint FKso9otr8br843nbpjk8202faay 
       foreign key (piattaforma_id) 
       references piattaforma;

    alter table if exists prodotto_piattaforma 
       add constraint FKke1e38s15ou25kw28dcjl3m3t 
       foreign key (prodotto_id) 
       references prodotto;
