
    create table account (
        id integer generated by default as identity,
        data_ora_aggiornamento timestamp(6),
        data_ora_creazione timestamp(6) not null,
        ruolo varchar(20) not null check (ruolo in ('ADMIN','CLIENTE')),
        cognome varchar(100) not null,
        nome varchar(100) not null,
        indirizzo varchar(255) not null,
        primary key (id)
    );

    create table carrello (
        account_id integer unique,
        id integer generated by default as identity,
        primary key (id)
    );

    create table carrello_riga (
        carrello_id integer not null,
        id integer generated by default as identity,
        prodotto_id integer not null,
        quantita integer not null,
        primary key (id),
        check (quantita > 0)
    );

    create table credenziale (
        account_id integer not null unique,
        id integer generated by default as identity,
        ultimo_login timestamp(6),
        email varchar(100) not null unique,
        password_hash varchar(255) not null,
        primary key (id)
    );

    create table ordine (
        account_id integer,
        id integer generated by default as identity,
        data_ora_aggiornamento timestamp(6),
        data_ora_creazione timestamp(6) not null,
        stato_ordine varchar(255) check (stato_ordine in ('IN_ATTESA','PAGATO','SPEDITO','CONSEGNATO','ANNULLATO')),
        primary key (id)
    );

    create table ordine_riga (
        id integer generated by default as identity,
        ordine_id integer not null,
        prezzo_unitario numeric(10,2) not null,
        prodotto_id integer not null,
        quantita integer not null,
        primary key (id),
        check (quantita > 0)
    );

    create table pagamento (
        id integer generated by default as identity,
        ordine_id integer not null,
        totale numeric(10,2) not null,
        data_ora_creazione timestamp(6) not null,
        metodo_pagamento varchar(20) not null check (metodo_pagamento in ('CARTA','PAYPAL','IBAN')),
        stato_pagamento varchar(255) not null check (stato_pagamento in ('IN_ATTESA','SUCCESSO','FALLITO')),
        primary key (id)
    );

    create table prodotto (
        anno_uscita integer,
        id integer generated by default as identity,
        prezzo numeric(10,2) not null,
        nome varchar(100) not null,
        cateogoria_prodotto varchar(255) not null,
        descrizione varchar(255) not null,
        primary key (id)
    );

    alter table if exists carrello 
       add constraint FKqe4cig9fabcp7d4sq1th1opq8 
       foreign key (account_id) 
       references account;

    alter table if exists carrello_riga 
       add constraint FK1kdw3wtgsdr5o2x1xbg7puej0 
       foreign key (carrello_id) 
       references carrello;

    alter table if exists carrello_riga 
       add constraint FK9l12co6tdh4f86puoe17spyky 
       foreign key (prodotto_id) 
       references prodotto;

    alter table if exists credenziale 
       add constraint FKsd0fonwnaypsmwkqag7m1dhvr 
       foreign key (account_id) 
       references account;

    alter table if exists ordine 
       add constraint FKpy50oev35mxm2shcvuye9likx 
       foreign key (account_id) 
       references account;

    alter table if exists ordine_riga 
       add constraint FKpplo0tcsgv8ypjgblpakdw7ej 
       foreign key (ordine_id) 
       references ordine;

    alter table if exists ordine_riga 
       add constraint FKoqpbw7rwrnsgxrqeu90oo08ue 
       foreign key (prodotto_id) 
       references prodotto;

    alter table if exists pagamento 
       add constraint FK7vk3ivb6us3276tk9exydpq31 
       foreign key (ordine_id) 
       references ordine;
