
    create table account (
        id integer generated by default as identity,
        aggiornato_il timestamp(6),
        creato_il timestamp(6) not null,
        ruolo varchar(20) not null check (ruolo in ('ADMIN','CLIENTE')),
        cognome varchar(100) not null,
        nome varchar(100) not null,
        cap varchar(255),
        citta varchar(255),
        paese varchar(255),
        via varchar(255),
        primary key (id)
    );

    create table carrello (
        account_id integer not null unique,
        id integer generated by default as identity,
        aggiornato_il timestamp(6),
        creato_il timestamp(6) not null,
        primary key (id)
    );

    create table carrello_riga (
        carrello_id integer not null,
        id integer generated by default as identity,
        prodotto_id integer not null,
        quantita integer not null,
        creato_il timestamp(6) not null,
        primary key (id),
        unique (carrello_id, prodotto_id),
        check (quantita > 0)
    );

    create table credenziale (
        account_id integer not null unique,
        id integer generated by default as identity,
        ultimo_login timestamp(6),
        email varchar(100) not null unique,
        password_hash varchar(255) not null,
        primary key (id)
    );

    create table messaggi_sistema (
        code varchar(255) not null,
        lang varchar(255) not null,
        messaggio varchar(255),
        primary key (code, lang)
    );

    create table ordine (
        account_id integer not null,
        id integer generated by default as identity,
        aggiornato_il timestamp(6),
        creato_il timestamp(6) not null,
        cap varchar(255),
        citta varchar(255),
        paese varchar(255),
        stato_ordine varchar(255) check (stato_ordine in ('IN_ATTESA','PAGATO','SPEDITO','CONSEGNATO','ANNULLATO')),
        via varchar(255),
        primary key (id)
    );

    create table ordine_riga (
        id integer generated by default as identity,
        ordine_id integer not null,
        prezzo_unitario numeric(10,2) not null,
        prodotto_id integer not null,
        quantita integer not null,
        primary key (id),
        check (quantita > 0)
    );

    create table pagamento (
        id integer generated by default as identity,
        ordine_id integer not null unique,
        totale numeric(10,2) not null,
        creato_il timestamp(6) not null,
        metodo_pagamento varchar(20) not null check (metodo_pagamento in ('CARTA_CREDITO','PAYPAL','BONIFICO')),
        stato_pagamento varchar(255) not null check (stato_pagamento in ('IN_ATTESA','SUCCESSO','FALLITO')),
        primary key (id)
    );

    create table prodotto (
        anno_uscita integer check (anno_uscita >= 1970 AND anno_uscita <= EXTRACT(YEAR FROM CURRENT_DATE)),
        id integer generated by default as identity,
        prezzo numeric(10,2) not null,
        piattaforma varchar(20) not null check (piattaforma in ('NES','SNES','N64','GAMECUBE','PS1','PS2','XBOX','MEGA_DRIVE','SATURN','DREAMCAST','GB','GBC','GBA','NDS','PSP','ATARI_2600','NEO_GEO')),
        nome varchar(100) not null,
        categoria varchar(255) not null check (categoria in ('CONSOLE','VIDEOGIOCO','CONTROLLER','ACCESSORIO')),
        descrizione TEXT not null,
        primary key (id)
    );

    alter table if exists carrello 
       add constraint FKqe4cig9fabcp7d4sq1th1opq8 
       foreign key (account_id) 
       references account;

    alter table if exists carrello_riga 
       add constraint FK1kdw3wtgsdr5o2x1xbg7puej0 
       foreign key (carrello_id) 
       references carrello;

    alter table if exists carrello_riga 
       add constraint FK9l12co6tdh4f86puoe17spyky 
       foreign key (prodotto_id) 
       references prodotto;

    alter table if exists credenziale 
       add constraint FKsd0fonwnaypsmwkqag7m1dhvr 
       foreign key (account_id) 
       references account;

    alter table if exists ordine 
       add constraint FKpy50oev35mxm2shcvuye9likx 
       foreign key (account_id) 
       references account;

    alter table if exists ordine_riga 
       add constraint FKpplo0tcsgv8ypjgblpakdw7ej 
       foreign key (ordine_id) 
       references ordine;

    alter table if exists ordine_riga 
       add constraint FKoqpbw7rwrnsgxrqeu90oo08ue 
       foreign key (prodotto_id) 
       references prodotto;

    alter table if exists pagamento 
       add constraint FK7vk3ivb6us3276tk9exydpq31 
       foreign key (ordine_id) 
       references ordine;
